spring:

#  sql:
#    init:
#      mode: always

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect:
          storage_engine: innodb
        format_sql: true
        show_sql: true
#    defer-datasource-initialization: true

  mail:
    host: smtp.gmail.com
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true

  thymeleaf:
    prefix:
      classpath: templates/
    suffix: .html
    cache: false

      #devtools:
      #livereload:
      #enabled: true
      #restart:
      #enabled: true

  redis:
    host: spring-boot-board_redis
    port: 6379
