spring:
  config:
    import:
      - classpath:/yaml/application-local-db.yml
      - classpath:/yaml/application-mail.yml
      - classpath:/yaml/application-real.properties
  profiles:
    group:
      logging: dev, mail
      local: local-db, mail
    active: local
  devtools:
    add-properties: false

#  jpa:
#    database-platform: org.hibernate.dialect.MySQL8Dialect
#    hibernate:
#      ddl-auto: none
#    properties:
#      hibernate:
#        dialect:
#          storage_engine: innodb
#        format_sql: true
#        show_sql: true
#    defer-datasource-initialization: true


  thymeleaf:
    prefix:
      classpath: templates/
    suffix: .html
    cache: false

      #devtools:
      #livereload:
      #enabled: true
      #restart:
      #enabled: true

  redis:
    host: spring-boot-board_redis
    port: 6379
