spring:
  config:
    import:
      - classpath:/yaml/application-local-db.yml
      - optional:classpath:/yaml/application-mail.yml
      - optional:classpath:/yaml/application-real-db.yml
  profiles:
    group:
      logging: dev, mail
      local: local-db, mail
      real: real-db, mail
  devtools:
    add-properties: false

  thymeleaf:
    prefix:
      classpath: templates/
    suffix: .html
    cache: false

      #devtools:
      #livereload:
      #enabled: true
      #restart:
      #enabled: true

  data:
    redis:
      host: localhost #spring-boot-board_redis
      port: 6379

app:
  security:
    h2-console:
      enabled: false
