spring:

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:~/board
    driver-class-name: org.h2.Driver
    username: sa

#  sql:
#    init:
#      mode: always

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
#    defer-datasource-initialization: true