spring:
  config:
    activate:
      on-profile: local-db

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:

  h2:
    console:
      enabled: true

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
        format_sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
      data-locations: classpath:/db/seed/local-data.sql,optional:file:src/main/resources/db/seed/local-account-data.sql

app:
  security:
    h2-console:
      enabled: true
