version: '3'

services:

  redis:
    container_name: ${PROJECT_NAME}_redis
    build:
      context: ./redis
    environment:
      # CLIENTPORT: ${REDIS_PORT}
      REDIS_EXPOSED_PORT: ${REDIS_EXPOSED_PORT}
      REDIS_LOG_DIR: ${REDIS_LOG_DIR}
    volumes:
      - ../redis-data:/data
      - ../logs/redis:${REDIS_LOG_DIR}
        #- ./redis/redis.cnf:/usr/local/bin/redis.conf
    networks:
      - app_net

  web:
    container_name: ${PROJECT_NAME}_web
    build:
      context: ./web
    volumes:
      - ../web/${PROJECT_NAME}/build/libs/${PROJECT_NAME}-${WEB_VERSION}.jar:/app.jar
    expose:
      - 8080
    ports:
      - ${WEB_HOST_PORT}:8080
    networks:
      - app_net
    depends_on:
      - redis
        #  restart: no

  # nginx:
  #   container_name: ${PROJECT_NAME}_nginx
  #   build:
  #     context: ./nginx
  #     args:
  #       - NGINX_ROOT_DIR=${NGINX_ROOT_DIR}
  #       - PROJECT_NAME=${PROJECT_NAME}
  #   volumes:
  #     - ./nginx/nginx.conf:${NGINX_ROOT_DIR}/conf.d/nginx.conf
  #   ports:
  #     - ${NGINX_HOST_PORT}:80
  #   depends_on:
  #     - web
  #   restart: always

networks:
  app_net:
    driver: bridge
    ipam:
      driver:
        default
